version: "3.9"
services:
  db:
    container_name: "api_db"
    image: postgres:14.3-alpine
    ports:
      - 5430:5432
    networks:
      - default
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
